"""Add importance and create_date fields for user model

Revision ID: 0722d1c4d8ed
Revises: 640f499f49e0
Create Date: 2020-03-31 01:51:15.339746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0722d1c4d8ed'
down_revision = '640f499f49e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_date')
    # ### end Alembic commands ###
