"""Add nickname column

Revision ID: 08ff828b8a5d
Revises: bd94eb83bde6
Create Date: 2020-04-05 22:58:44.873889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ff828b8a5d'
down_revision = 'bd94eb83bde6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
