"""Add column image url

Revision ID: 180bf703de88
Revises: bbfd684522c3
Create Date: 2020-04-06 18:24:31.765897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180bf703de88'
down_revision = 'bbfd684522c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
