"""Add table post

Revision ID: 541f8737d3bb
Revises: 5f1e817237b8
Create Date: 2020-04-07 19:46:51.297249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541f8737d3bb'
down_revision = '5f1e817237b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
