"""remove registration date column

Revision ID: 55ecd9ddb280
Revises: 715f869ab2c8
Create Date: 2020-04-13 12:12:22.211286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ecd9ddb280'
down_revision = '715f869ab2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
