"""Add post_id in comment model

Revision ID: 715f869ab2c8
Revises: f0931d399081
Create Date: 2020-04-12 15:59:14.996417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715f869ab2c8'
down_revision = 'f0931d399081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('post_id', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
