"""Add date_piblication_string in post model

Revision ID: 7447a8388d46
Revises: d8de31ed4795
Create Date: 2020-04-09 22:27:59.589922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7447a8388d46'
down_revision = 'd8de31ed4795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_date_string', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('publication_date_string')

    # ### end Alembic commands ###
