""" Rename column content to content_url

Revision ID: d92e55f1ccf4
Revises: fb4de988cacf
Create Date: 2020-04-08 20:11:36.762751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92e55f1ccf4'
down_revision = 'fb4de988cacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_url', sa.Text(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.drop_column('content_url')

    # ### end Alembic commands ###
