""" Rename column data to content in table post

Revision ID: fb4de988cacf
Revises: 116fc06a31e3
Create Date: 2020-04-08 20:05:41.899487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4de988cacf'
down_revision = '116fc06a31e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.TEXT(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
